### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by aizenbit** [aizenbit/Scribbler#2]
Список того, что я хочу не забыть сделать, если когда-нибудь решу сделать. Не обязательно в порядке важности.
#### Новые возможности программы:
- [ ] Поддержка лигатур
- [x] Настройка ширины пробела
- [ ] Возможность рисовать ~~члены~~ на полях
- [ ] Эффект сползания строк и скачущих слов
- [x] Динамические поля
- [ ] Эффект зачёркиваний
- [ ] Поддержка частично слитного написания
- [ ] Поддержка растровых шрифтов
- [x] Печать разметки листа
#### Просто улучшения:
- [x] Исправить настройки печати
- [ ] Сделать перенос букв из графического редактора в программу более удобным для пользователя. На самом деле, он и сейчас ничего, но занимает много времени
- [ ] Сделать соединительные линии между буквами изогнутыми. Думаю, так текст будет смотреться естественнее
- [ ] Возможность поворачивать изображение буквы в редакторе шрифтов
- [ ] В редакторе шрифтов добавить привязку точек к концам линий и жёлтого прямоугольника к границам букв
- [ ] Настройка горячих клавиш
- [x] Убрать точки у небукв в редакторе шрифтов
#### Улучшение кода и всё остальное:
- [x] Покопаться в коде функции SvgView::renderText() и всех, которые она вызывает, потому что писать новый код, связанный с преобразованием текста, становится проблематично. Может это заодно позволит избавиться от некоторых глюков
- [x] Добавить в код больше пояснений (комментариев), потому что с самодокументацией у меня не очень.
- [ ] Уменьшить количество говнокода (в процессе)
- [x] ~~Написать тесты и~~ прикрутить Travis CI
- [ ] Возможно, стоит уменьшить частоту обращений к файлу настроек

**Comment by ghost** [comment]
Привет, 
предлагаю объединить усилия и дополнить твой код таким образом, чтобы можно было на выходе получить стандартный Gcode для 3D принтера.
Тогда можно будет снабдив любой стандартный 3D принтер ручкой вместо печатной головы - писать конспекты в реалии (ну или подписывать открытки).
Сам я не программист (хотя код свободно читаю и понимаю), зато занимаюсь разработкой 3D принтеров, включая модификацию и фиксы для прошивки.
Не нашел твоих контактов, пиши на setar@roboforum.ru

**Comment by aizenbit** [comment]
Привет!

Идея любопытная, однако помочь ничем не могу: сейчас у меня банально не хватит сил и времени на такой проект. К тому же, как видно по этому todo, есть много вещей, которые хотелось бы сделать, и пока что они для меня более приоритетны. 
Тем не менее, если у вас что-то получится с этой идеей - дайте знать. :)

**Comment by ghost** [comment]
хорошо, оставь плиз контактную почту

**Comment by santaklouse** [comment]
Здравствуйте, хотелось бы знать, планируете ли вы поддержку Mac OS X?
Если да, то я мог бы помочь с этим.
Спасибо.

**Comment by ghost** [comment]
а вопрос собственно кому ?
P.S. я  (в психологии и наличию железа) мультиплатформенный, сейчас пишу с мака,

**Comment by santaklouse** [comment]
@setar сорри, вопрос к разработчику Scribbler - @aizenbit.

**Comment by aizenbit** [comment]
@santaklouse В ближайшее время поддержку OS X не планирую, потому что мака у меня нет, а на виртуальную машину для тестирования или хотя бы просто кросс-компиляцию нужно найти время разобраться. В будущем - возможно, но обещать ничего не буду.

**Comment by nazbav** [comment]
Еще можно добавить возможность создавать таблицы, и списки.

**Comment by heavywar** [comment]
Побольше бы комментариев в коде.

**Comment by Xabab** [comment]
Конечно, понимаю, что проект скорее всего заброшен, но пара идей:
- импорт шрифтов, что бы не прописывать КАЖДЫЙ глиф
- может быть, создание глифов в самом приложении
- или хотя бы человеческий импорт svg из inkscape'а
- добавить скобки ( "(", ")" ) в список согласных букв, что бы их не отрывало при переносе на следующую строку
- конец линий утончать к концу, имитируя подъем ручки от листа

**Comment by aizenbit** [comment]
Идеи хорошие) Но да, маловероятно, что я буду добавлять что-то новое. Тем более что сейчас в проект сложно вносить какие-то большие изменения, сначала было бы неплохо провести рефакторинг.

**Comment by Xabab** [comment]
Насыпь документации - может кто и возьмётся тогда.

**Comment by ghost** [comment]
> прикрутить Travis CI

А прикрутите сборку AppImage и вигрузку на GitHub ночнушек

0. [x] Создать `../blob/master/.travis.yml`
1. https://github.com/appimage/AppImageKit
1.1. https://github.com/probonopd/linuxdeployqt
1.2 https://github.com/linuxdeploy
2. https://github.com/probonopd/uploadtool
3. [ ] Включить для Travis CI пушинг в GitHub releases для репы.

Можно так же и сборку под Mac OS на Travis CI тоже прикрутить

**Comment by ghost** [comment]
Возможно, полезная ссылка

- https://github.com/Unbinilium/Handwriter

> “A lightweight tool for you to generate handwriting-liked text for printing” (`C++`/`Python3`)

**Comment by sergeyfk05** [comment]
Можно экспортировать в SVG?

**Comment by aizenbit** [comment]
> 
> 
> Можно экспортировать в SVG?

Такой возможности нет.

**Comment by annoyinganime** [comment]
А насколько сложно добавить возможность экспорта svg? Cделал бы сам, но я к сожалению не настолько хорош в c++

**Comment by aizenbit** [comment]
Емнип в Qt нет возможности создавать и редактировать svg. Так что надо найти библиотеку, позволяющую это делать, подключить её, и потом, собственно, создать svg, используя информацию из SvgView. Должно быть не очень сложно, но времени на это уйдёт немало.

А для чего нужен экспорт в svg?

**Comment by annoyinganime** [comment]
Для того, чтобы можно было воспроизвести текст на плоттере. Эта программа генерирует текст, очень похожий на мой почерк, однако если печатать на обычном принтере - видны пиксели. Пробовал перегонять png в svg с помощью inkscape и centerline-trace, однако там между отдельными линиями остаётся очень много места, и это заметно

**Comment by sergeyfk05** [comment]
Я пытался наговнокодить экспорт в SVG. Получилось нормально это сделать только создав строку, в которой я писал SVG строку. И то у меня было множество багов и я отказался от этой идеи. Позже получилось взять рукописный текст с онлайн сервисов и в CorelDraw перевести в вектор по center line. Затем в Inkscape сгенерировал скрипт для плоттера. В итоге плоттер писал почти как человек.

**Comment by aizenbit** [comment]
Печать на плоттере? Ого.
Вообще для размера пикселей есть настройка dpi, на вкладке "дополнительные". По умолчанию там стоит 300, как самое распространённое значение, но можно поставить, например, 600 или сколько максимально поддерживает конкретный принтер/плоттер. Это решит проблему?
